@echo off
chcp 65001 > nul
set TEST_AUTH_TOKEN=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ0ZXN0LXBlcmZvcm1hbmNlQGV4YW1wbGUuY29tIiwidXNlcl9pZCI6IjJjOWM0M2I1LWFhMmMtNDljYy05YmMzLTUxNzhmYTdiN2Y3YyIsImVtYWlsIjoidGVzdC1wZXJmb3JtYW5jZUBleGFtcGxlLmNvbSIsIm5hbWUiOiJQZXJmb3JtYW5jZSBUZXN0IFVzZXIiLCJyb2xlIjoiZWRpdG9yIiwicHJvdmlkZXIiOiJ0ZXN0IiwiZXhwIjoxNzYwNjYwMjIyLCJ0eXBlIjoiYWNjZXNzIn0.pje4n782aAXChj5zScPBhQ6T8FYa_TYYPrhU4sGnTTY
set PYTHONIOENCODING=utf-8
D:\Projects\DEV\AI-Doc-Editor\backend\.venv\Scripts\python.exe tests\performance\setup_perf_test.py --gutenberg --target-chunks 100
