nodeLinker: node-modules
enableGlobalCache: true
enableScripts: true
supportedArchitectures:
  os: ["current"]
  cpu: ["current"]
packageExtensions:
  "@electron/rebuild@*":
    peerDependencies:
      electron: "*"
