"""
Outline database model for T-06 Section Generation.

This module defines the SQLAlchemy ORM model for outlines generated by
T-05 Planner Service and used by T-06 Section Generation.
"""

from datetime import datetime
from sqlalchemy import Column, String, DateTime, Float, Text
from sqlalchemy.types import TypeDecorator, CHAR
from sqlalchemy.dialects.postgresql import UUID as PG_UUID, JSONB
from sqlalchemy.dialects.sqlite import JSON
import uuid

from app.db.session import Base


class UUID(TypeDecorator):
    """
    Platform-independent UUID type.

    Uses PostgreSQL's UUID type when available, otherwise uses CHAR(36)
    for SQLite compatibility.
    """

    impl = CHAR
    cache_ok = True

    def load_dialect_impl(self, dialect):
        if dialect.name == "postgresql":
            return dialect.type_descriptor(PG_UUID(as_uuid=True))
        else:
            return dialect.type_descriptor(CHAR(36))

    def process_bind_param(self, value, dialect):
        if value is None:
            return value
        elif dialect.name == "postgresql":
            return value
        else:
            if isinstance(value, uuid.UUID):
                return str(value)
            else:
                return str(uuid.UUID(value))

    def process_result_value(self, value, dialect):
        if value is None:
            return value
        else:
            if isinstance(value, uuid.UUID):
                return value
            else:
                return uuid.UUID(value)


class JSONType(TypeDecorator):
    """
    Platform-independent JSON type.

    Uses PostgreSQL's JSONB when available, otherwise uses SQLite's JSON.
    """

    impl = Text
    cache_ok = True

    def load_dialect_impl(self, dialect):
        if dialect.name == "postgresql":
            return dialect.type_descriptor(JSONB())
        else:
            return dialect.type_descriptor(JSON())

    def process_bind_param(self, value, dialect):
        if value is None:
            return value
        import json

        return json.dumps(value) if dialect.name == "sqlite" else value

    def process_result_value(self, value, dialect):
        if value is None:
            return value
        if dialect.name == "sqlite":
            import json

            return json.loads(value)
        return value


class Outline(Base):
    """
    Outline model for document structure planning.

    Stores outlines generated by T-05 Planner Service for use in T-06 Section Generation.
    Outlines define the hierarchical structure (H1→H2→H3) for document generation.
    """

    __tablename__ = "outlines"

    # Primary key
    id = Column(UUID(), primary_key=True, default=uuid.uuid4, index=True)

    # Associated document (optional - may be null for standalone outlines)
    document_id = Column(UUID(), nullable=True, index=True)

    # Ownership
    user_id = Column(UUID(), nullable=False, index=True)

    # Outline structure (JSON serialized from PlanResponse.outline)
    # Format: {"headings": [...HeadingNode...], "total_headings": N}
    outline_structure = Column(JSONType, nullable=False)

    # Quality metrics (from PlanResponse.quality_metrics)
    # Format: {"quality_score": 0.85, "h1_count": 3, "h2_count": 6, ...}
    quality_metrics = Column(JSONType, nullable=True)

    # Quality score (denormalized for indexing/filtering)
    quality_score = Column(Float, nullable=False, default=0.0, index=True)

    # Generation metadata
    generation_mode = Column(String(20), nullable=False)  # "outline-guided" or "single-shot"
    model_used = Column(String(50), nullable=False)  # e.g., "gpt-4o-mini"
    tokens_used = Column(String(50), nullable=True)  # Total tokens consumed
    generation_time_ms = Column(String(50), nullable=False)  # Generation time

    # Original prompt
    original_prompt = Column(Text, nullable=False)

    # Timestamps
    created_at = Column(DateTime, nullable=False, default=datetime.utcnow, index=True)

    def __repr__(self):
        return (
            f"<Outline(id={self.id}, user_id={self.user_id}, "
            f"quality_score={self.quality_score}, mode={self.generation_mode})>"
        )
