"""
Section database model for T-06 Section Generation.

This module defines the SQLAlchemy ORM model for generated document sections
streamed via WebSocket in T-06.
"""

from datetime import datetime
from sqlalchemy import Column, String, Integer, DateTime, Text, ForeignKey
from sqlalchemy.types import TypeDecorator, CHAR
from sqlalchemy.dialects.postgresql import UUID as PG_UUID
import uuid

from app.db.session import Base


class UUID(TypeDecorator):
    """
    Platform-independent UUID type.

    Uses PostgreSQL's UUID type when available, otherwise uses CHAR(36)
    for SQLite compatibility.
    """

    impl = CHAR
    cache_ok = True

    def load_dialect_impl(self, dialect):
        if dialect.name == "postgresql":
            return dialect.type_descriptor(PG_UUID(as_uuid=True))
        else:
            return dialect.type_descriptor(CHAR(36))

    def process_bind_param(self, value, dialect):
        if value is None:
            return value
        elif dialect.name == "postgresql":
            return value
        else:
            if isinstance(value, uuid.UUID):
                return str(value)
            else:
                return str(uuid.UUID(value))

    def process_result_value(self, value, dialect):
        if value is None:
            return value
        else:
            if isinstance(value, uuid.UUID):
                return value
            else:
                return uuid.UUID(value)


class Section(Base):
    """
    Section model for generated document content.

    Stores individual sections generated by T-06 Section Generation Service
    via WebSocket streaming. Each section corresponds to a heading in the outline.
    """

    __tablename__ = "sections"

    # Primary key
    id = Column(UUID(), primary_key=True, default=uuid.uuid4, index=True)

    # Associated document (optional)
    document_id = Column(UUID(), nullable=True, index=True)

    # Associated outline (foreign key to outlines table)
    outline_id = Column(UUID(), ForeignKey("outlines.id"), nullable=False, index=True)

    # Section metadata
    section_title = Column(String(500), nullable=False)
    section_level = Column(Integer, nullable=False)  # 1=H1, 2=H2, 3=H3
    heading_id = Column(String(50), nullable=False)  # e.g., "H1", "H1.1", "H1.2.1"

    # Section position in document (for ordering)
    section_order = Column(Integer, nullable=False, default=0, index=True)

    # Generated content
    content = Column(Text, nullable=False)

    # Statistics
    word_count = Column(Integer, nullable=False, default=0)
    tokens_used = Column(Integer, nullable=False, default=0)
    generation_time_ms = Column(Integer, nullable=False, default=0)

    # Ownership
    user_id = Column(UUID(), nullable=False, index=True)

    # Timestamps
    created_at = Column(DateTime, nullable=False, default=datetime.utcnow, index=True)

    def __repr__(self):
        return (
            f"<Section(id={self.id}, title={self.section_title}, "
            f"level={self.section_level}, words={self.word_count})>"
        )
