#!/bin/bash
# Install git hooks for status tracking validation
# Part of Phase 3: Automated Status Tracking (Pre-commit Hooks)
#
# Usage: bash scripts/install-status-hooks.sh
#        yarn repo:status:hooks:install

set -e

# Get the project root directory
PROJECT_ROOT="$(git rev-parse --show-toplevel 2>/dev/null || pwd)"
cd "$PROJECT_ROOT"

# Colors for output
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

HOOK_DIR=".git/hooks"
HOOK_FILE="$HOOK_DIR/pre-commit"
VALIDATION_SCRIPT="scripts/pre-commit-status-validation.sh"

echo -e "${BLUE}🔧 Status Tracking Hooks Installer${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

# Verify .git directory exists
if [[ ! -d ".git" ]]; then
    echo -e "${YELLOW}⚠️  Not a git repository (no .git directory found)${NC}"
    echo "   Please run this script from the project root."
    exit 1
fi

# Create hooks directory if missing
mkdir -p "$HOOK_DIR"

# Make validation script executable
if [[ -f "$VALIDATION_SCRIPT" ]]; then
    chmod +x "$VALIDATION_SCRIPT"
    echo -e "${GREEN}✅ Made validation script executable${NC}"
else
    echo -e "${YELLOW}⚠️  Validation script not found: $VALIDATION_SCRIPT${NC}"
    echo "   Creating it now..."
    exit 1
fi

# Check if pre-commit hook already exists
if [[ -f "$HOOK_FILE" ]]; then
    echo -e "${YELLOW}⚠️  Pre-commit hook already exists${NC}"
    echo "   Location: $HOOK_FILE"
    echo ""

    # Check if our validation is already integrated
    if grep -q "pre-commit-status-validation.sh" "$HOOK_FILE"; then
        echo -e "${GREEN}✅ Status validation already integrated${NC}"
        echo "   No changes needed."
        echo ""
        exit 0
    fi

    echo "   Appending status validation logic to existing hook..."
    echo ""

    # Append our validation to existing hook
    cat >> "$HOOK_FILE" <<'HOOK_APPEND'

# ═══════════════════════════════════════════════════════════════
# Status Tracking Validation (Phase 3)
# Validates hierarchy consistency when T-XX-STATUS.md files change
# ═══════════════════════════════════════════════════════════════

# Run status validation script
if [[ -f "scripts/pre-commit-status-validation.sh" ]]; then
    bash scripts/pre-commit-status-validation.sh || exit 1
fi
HOOK_APPEND

    echo -e "${GREEN}✅ Appended status validation to existing hook${NC}"
    echo ""
else
    # Create new pre-commit hook from scratch
    echo "   Creating new pre-commit hook..."
    echo ""

    cat > "$HOOK_FILE" <<'HOOK_CONTENT'
#!/bin/bash
# Pre-commit hook for AI Document Editor
# Auto-generated by scripts/install-status-hooks.sh

# ═══════════════════════════════════════════════════════════════
# Status Tracking Validation (Phase 3)
# Validates hierarchy consistency when T-XX-STATUS.md files change
# ═══════════════════════════════════════════════════════════════

# Run status validation script
if [[ -f "scripts/pre-commit-status-validation.sh" ]]; then
    bash scripts/pre-commit-status-validation.sh || exit 1
fi

exit 0
HOOK_CONTENT

    chmod +x "$HOOK_FILE"
    echo -e "${GREEN}✅ Created new pre-commit hook${NC}"
    echo ""
fi

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo -e "${GREEN}✅ Status tracking hooks installed successfully${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo -e "${BLUE}Behavior:${NC}"
echo "  • Commits touching T-XX-STATUS.md will trigger validation"
echo "  • Validation checks hierarchy consistency (Task → WP → Release → Project)"
echo "  • Commit blocked if inconsistencies detected"
echo "  • Use /sync-project-status to auto-fix before committing"
echo ""
echo -e "${BLUE}Override (NOT recommended):${NC}"
echo "  git commit --no-verify    (skips all hooks)"
echo ""
echo -e "${GREEN}Happy status tracking! 🚀${NC}"
echo ""
