"""Create outlines table for T-05/T-06 integration

Revision ID: 007
Revises: 006
Create Date: 2025-10-21 00:00:00.000000

T-05: Planner Service - Document Outline Generation
T-06: Section Generation - Outline persistence for section streaming

Creates outlines table for storing document outlines generated by T-05
Planner Service and used by T-06 Section Generation Service.

Features:
- Outline structure storage (JSON with hierarchical headings)
- Quality metrics tracking (quality_score, generation_mode, etc.)
- User ownership tracking (user_id)
- Optional document association (document_id)
- Indexes for common query patterns
"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = "007"
down_revision = "006"
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Create outlines table and indexes"""

    # Create outlines table
    op.create_table(
        "outlines",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True, nullable=False),
        sa.Column("document_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("user_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("outline_structure", postgresql.JSONB(), nullable=False),
        sa.Column("quality_metrics", postgresql.JSONB(), nullable=True),
        sa.Column("quality_score", sa.Float(), nullable=False, server_default="0.0"),
        sa.Column("generation_mode", sa.String(20), nullable=False),
        sa.Column("model_used", sa.String(50), nullable=False),
        sa.Column("tokens_used", sa.String(50), nullable=True),
        sa.Column("generation_time_ms", sa.String(50), nullable=False),
        sa.Column("original_prompt", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            nullable=False,
            server_default=sa.text("CURRENT_TIMESTAMP"),
        ),
    )

    # Create indexes for common query patterns
    op.create_index("ix_outlines_id", "outlines", ["id"])
    op.create_index("ix_outlines_document_id", "outlines", ["document_id"])
    op.create_index("ix_outlines_user_id", "outlines", ["user_id"])
    op.create_index("ix_outlines_quality_score", "outlines", ["quality_score"])
    op.create_index("ix_outlines_created_at", "outlines", ["created_at"])

    # Composite index for user outline listing (most common query)
    op.create_index(
        "ix_outlines_user_listing",
        "outlines",
        ["user_id", "created_at"],
        postgresql_using="btree",
    )

    # Composite index for high-quality outline filtering
    op.create_index(
        "ix_outlines_quality_filter",
        "outlines",
        ["user_id", "quality_score", "created_at"],
        postgresql_using="btree",
    )


def downgrade() -> None:
    """Drop outlines table and indexes"""

    # Drop indexes
    op.drop_index("ix_outlines_quality_filter", "outlines")
    op.drop_index("ix_outlines_user_listing", "outlines")
    op.drop_index("ix_outlines_created_at", "outlines")
    op.drop_index("ix_outlines_quality_score", "outlines")
    op.drop_index("ix_outlines_user_id", "outlines")
    op.drop_index("ix_outlines_document_id", "outlines")
    op.drop_index("ix_outlines_id", "outlines")

    # Drop table
    op.drop_table("outlines")
